include:
  - docker-compose.yml

services:
  nginx:
    build: ./nginx
    container_name: nginx-dev
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - transcendence_net

  frontend:
    build: ./frontend
    container_name: frontend-dev
    volumes:
      - ./frontend:/app:rw
    ports:
      - "5173:5173"
    networks:
      - transcendence_net
    command: npm run dev

  backend:
    build: ./backend
    container_name: backend-dev
    volumes:
      - ./database:/database:ro
      - ./backend:/backend:ro
      - ./backend/src:/app/src:ro
      - ./backend/package.json:/app/package.json:ro
      - ./backend/tsconfig.json:/app/tsconfig.json:ro
      - ./backend/nest-cli.json:/app/nest-cli.json:ro
    ports:
      - "3000:3000"
    networks:
      - transcendence_net
    command: npm run start:dev

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
      target: development
    container_name: auth-service-dev
    ports:
      - "3001:3001"
    volumes:
      - ./services/auth-service/src:/app/src:ro
      - ./services/auth-service/package.json:/app/package.json:ro
      - ./services/auth-service/tsconfig.json:/app/tsconfig.json:ro
      - ./services/auth-service/nest-cli.json:/app/nest-cli.json:ro
    networks:
      - transcendence_net
    command: npm run start:dev

  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
      target: development
    container_name: api-gateway-dev
    ports:
      - "3002:3002"
    volumes:
      - ./services/api-gateway/src:/app/src:ro
      - ./services/api-gateway/package.json:/app/package.json:ro
      - ./services/api-gateway/tsconfig.json:/app/tsconfig.json:ro
      - ./services/api-gateway/nest-cli.json:/app/nest-cli.json:ro
    networks:
      - transcendence_net
    command: npm run start:dev

  db:
    container_name: postgres-dev
    ports:
      - "5432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data
      - ./backend/database/init:/docker-entrypoint-initdb.d:ro
    networks:
      - transcendence_net

volumes:
  db_data_dev:
