include:
  - docker-compose.yml

services:
  # === Core Application ===

  frontend:
    build: ./frontend
    container_name: frontend-dev
    volumes:
      - ./frontend/package.json:/app/package.json:ro
      - ./frontend/tsconfig.json:/app/tsconfig.json:ro
      - ./frontend/vite.config.js:/app/vite.config.js:ro
      - ./frontend/public:/app/public:rw
      - ./frontend/src:/app/src:rw
    ports:
      - "5173:5173"
    networks:
      - transcendence_net
    command: npm run dev

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend-dev
    volumes:
      - ./database:/database:ro
      - ./backend/src:/app/backend/src:ro
      - ./backend/package.json:/app/backend/package.json:ro
      - ./backend/tsconfig.json:/app/backend/tsconfig.json:ro
      - ./backend/nest-cli.json:/app/backend/nest-cli.json:ro
    ports:
      - "3000:3000"
    networks:
      - transcendence_net
    command: npm run start:dev

  # === Microservices ===

  auth-service:
    build:
      context: .
      dockerfile: ./services/auth-service/Dockerfile
      target: development
    container_name: auth-service-dev
    ports:
      - "3001:3001"
    volumes:
      - ./services/auth-service/src:/app/./services/auth-service/src:ro
      - ./services/auth-service/package.json:/app/./services/auth-service/package.json:ro
      - ./services/auth-service/tsconfig.json:/app/./services/auth-service/tsconfig.json:ro
      - ./services/auth-service/nest-cli.json:/app/./services/auth-service/nest-cli.json:ro
    networks:
      - transcendence_net
    command: npm run start:dev

  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
      target: development
    container_name: api-gateway-dev
    ports:
      - "3002:3002"
    volumes:
      - ./services/api-gateway/src:/app/src:ro
      - ./services/api-gateway/package.json:/app/package.json:ro
      - ./services/api-gateway/tsconfig.json:/app/tsconfig.json:ro
      - ./services/api-gateway/nest-cli.json:/app/nest-cli.json:ro
    networks:
      - transcendence_net
    command: npm run start:dev

  game-service:
    build:
      context: ./services/game-service
      dockerfile: Dockerfile
      target: development
    container_name: game-service-dev
    ports:
      - "3003:3003"
    volumes:
      - ./services/game-service/src:/app/src:ro
      - ./services/game-service/package.json:/app/package.json:ro
      - ./services/game-service/tsconfig.json:/app/tsconfig.json:ro
      - ./services/game-service/nest-cli.json:/app/nest-cli.json:ro
    networks:
      - transcendence_net
    command: npm run start:dev

  # === Infrastructure ===

  db:
    container_name: postgres-dev
    ports:
      - "5432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data
      - ./database/init/schema/00-schema.sql:/docker-entrypoint-initdb.d/00-schema.sql:ro
    networks:
      - transcendence_net

  nginx:
    build: ./nginx
    container_name: nginx-dev
    ports:
      # - "80:80" // comment out port for compatability with hive's computers
      - "8080:8080"
    networks:
      - transcendence_net
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:8080/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data_dev:
