services:
  db:
    image: postgres:17-alpine
    container_name: postgres_dev
    environment:
      POSTGRES_USER: transcendence
      POSTGRES_PASSWORD: transcendence
      POSTGRES_DB: transcendence
    ports:
      - "5432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data
      - ./backend/src/database/init:/docker-entrypoint-initdb.d:ro

volumes:
  db_data_dev:
