include:
  - docker-compose.yml

services:
  # === Core Application ===

  frontend:
    networks:
      - transcendence_net
    command: ["npm", "run", "build"]

  backend:
    expose:
      - "3000"
    volumes:
      - ./database:/database:ro
    networks:
      - transcendence_net

  # === Microservices ===

  api-gateway:
    expose:
      - "3002"
    networks:
      - transcendence_net

  auth-service:
    expose:
      - "3001"
    networks:
      - transcendence_net

  game-service:
    expose:
      - "3003"
    networks:
      - transcendence_net

  # === Infrastructure ===

  db:
    expose:
      - "5432"
    volumes:
      - db_data_prod:/var/lib/postgresql/data
    networks:
      - transcendence_net

  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - frontend_build:/usr/share/nginx/html:ro
      - ./nginx/cert:/etc/nginx/cert:ro
    networks:
      - transcendence_net

volumes:
  db_data_prod:
  frontend_build:
