include:
  - docker-compose.yml

services:
  # === Core Application ===

  frontend:
    command: ["npm", "run", "build"]

  core:
    expose:
      - "3000"

  # === Microservices ===

  gateway:
    expose:
      - "3002"

  auth:
    expose:
      - "3001"

  game:
    expose:
      - "3003"

  # === Infrastructure ===

  db:
    expose:
      - "5432"
    volumes:
      - db_data_prod:/var/lib/postgresql/data
      - ./database/init/schema/00-schema.sql:/docker-entrypoint-initdb.d/00-schema.sql:ro

  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - frontend_build:/usr/share/nginx/html:ro
      - ./nginx/cert:/etc/nginx/cert:ro

volumes:
  db_data_prod:
  frontend_build:
