services:

  frontend:
    build: ./frontend
    container_name: frontend
    env_file:
      - ./.env
    networks:
      - transcendence_net

  # === Backend Microservices ===

  gateway:
    build: ./backend/gateway
    container_name: gateway
    env_file:
      - ./.env
    depends_on:
      core:
        condition: service_healthy
      game:
        condition: service_healthy
      auth:
        condition: service_healthy
    networks:
      - transcendence_net
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://gateway:3002/api/health || exit 1"]
      interval: 5s
      timeout: 2s
      start_period: 60s
      retries: 1

  core:
    build: ./backend/core
    container_name: core
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - transcendence_net
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://core:3000/api/core/health || exit 1"]
      interval: 5s
      timeout: 2s
      start_period: 60s
      retries: 1

  auth:
    build: ./backend/auth
    container_name: auth
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - transcendence_net
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://auth:3001/api/auth/health || exit 1"]
      interval: 5s
      timeout: 2s
      start_period: 60s
      retries: 1

  game:
    build: ./backend/game
    container_name: game
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - transcendence_net
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://game:3003/api/game/health || exit 1"]
      interval: 5s
      timeout: 2s
      start_period: 60s
      retries: 1

  # === Infrastructure ===

  db:
    image: postgres:17-alpine
    container_name: postgres
    env_file:
      - ./.env
    volumes:
      - ./database/init/schema/00-schema.sql:/docker-entrypoint-initdb.d/00-schema.sql:ro
    networks:
      - transcendence_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB || exit 1"]
      interval: 5s
      timeout: 2s
      start_period: 60s
      retries: 1

  nginx:
    build: ./nginx
    container_name: nginx
    env_file:
      - ./.env
    networks:
      - transcendence_net
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://127.0.0.1 || exit 1"]
      interval: 5s
      timeout: 2s
      start_period: 60s
      retries: 1

  healthchecker:
    image: alpine:3.23.3
    depends_on:
      nginx:
        condition: service_healthy
      gateway:
        condition: service_healthy
    networks:
      - transcendence_net

networks:
  transcendence_net:
