include:
  - docker-compose.yml

services:

  frontend:
    build:
      target: production
    container_name: frontend-prod

  # === Backend Microservices ===

  gateway:
    build:
      target: production
    container_name: gateway-prod
    expose:
      - "3002"

  core:
    build:
      target: production
    container_name: core-prod
    expose:
      - "3000"

  auth:
    build:
      target: production
    container_name: auth-prod
    expose:
      - "3001"

  game:
    build:
      target: production
    container_name: game-prod
    expose:
      - "3003"

  # === Infrastructure ===

  db:
    container_name: db-prod
    expose:
      - "5432"
    volumes:
      - db_data_prod:/var/lib/postgresql/data

  nginx:
    container_name: nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - frontend_build:/usr/share/nginx/html:ro
      - ./nginx/cert:/etc/nginx/cert:ro

volumes:
  db_data_prod:
  frontend_build:
